name: auto check

on:
  push:
    branches:
      - main
      - master

jobs:
  check:
    name: auto check
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: install tamac
        shell: pwsh
        run: ./tools/setup.ps1 -Tool tamac
      - name: dictionary check
        shell: pwsh
        run: ./tools/check-dic.ps1 -Ci
